apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tmm-privatebin
  namespace: privatebin
spec:
  interval: 1m
  chart:
    spec:
      chart: privatebin
      sourceRef:
        kind: HelmRepository
        name: privatebin
        namespace: privatebin
      interval: 1m
  test:
    enable: true
  upgrade:
    remediation:
      remediateLastFailure: false
  values:
    replicaCount: 2
    name: tmm-privatebin
    #service:
      #type: LoadBalancer
    ingress:
      enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-privbin
      ingress.kubernetes.io/force-ssl-redirect: "true"
      kubernetes.io/ingress.class: contour
      kubernetes.io/tls-acme: "true"
    hosts:
    - host: privatebin.coreydinkens.com
      paths:
        - path: "/"
          pathType: Prefix
          backend:
            service:
              name: tmm-privatebin
              port:
                number: 80
    tls:
    - secretName: privatebin-cert-tls
      hosts:
      - privatebin.coreydinkens.com
