apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tmm-privatebin
  namespace: privatebin
spec:
  interval: 1m
  chart:
    spec:
      chart: privatebin
      sourceRef:
        kind: HelmRepository
        name: privatebin
        namespace: privatebin
      interval: 1m
  values:
    replicaCount: 2
    name: tmm-privatebin
    service:
      type: LoadBalancer
    #ingress.enabled: true
    #ingress.hosts.host: privatebin.tanzu.system
