# helmrepo.yaml
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: privatebin
  namespace: default
spec:
  interval: 1m0s
  url: https://privatebin.github.io/helm-chart