apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: privatebin-cert
  namespace: privatebin
spec:
  secretName: privatebin-cert-tls
  duration: 2160h
  renewBefore: 360h
  subject:
    organizations:
    - coreydinkens
  commonName: privatebin.tmc.coreydinkens.com
  isCA: false
  privateKey:
    size: 2048
    algorithm: RSA
    encoding: PKCS1
  dnsNames:
  - privatebin.tmc.coreydinkens.com
  issuerRef:
    name: letsencrypt-clusterissuer
    kind: ClusterIssuer